<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="Cashier.AccountSummary3Test" tests="3" time="160.566" ignored="6" failures="1" timestamp="22 Mar 2017 10:04:50 GMT" skipped="0" hostname="NP-SADEKUNLE" errors="0">
  <testcase name="AccountGameHistorytest" time="47.730" classname="Cashier.AccountSummary3Test"/>
  <testcase name="AccountSessiontest" time="47.735" classname="Cashier.AccountSummary3Test"/>
  <testcase name="AccountBonusestest" time="65.101" classname="Cashier.AccountSummary3Test">
    <failure type="java.lang.AssertionError" message="Element not found - cashier_Withdraw_xpath">
      <![CDATA[java.lang.AssertionError: Element not found - cashier_Withdraw_xpath
	at org.testng.Assert.fail(Assert.java:94)
	at Base.TestBase.click(TestBase.java:186)
	at Cashier.AccountSummary3Test.AccountBonusestest(AccountSummary3Test.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1289)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- AccountBonusestest -->
  <testcase name="DepositLimitTest" classname="Cashier.AccountSummaryTest">
    <skipped/>
  </testcase> <!-- DepositLimitTest -->
  <testcase name="SelfExclusiontest" classname="Cashier.AccountSummaryTest">
    <skipped/>
  </testcase> <!-- SelfExclusiontest -->
  <testcase name="TimeoutOptionTest" classname="Cashier.AccountSummaryTest">
    <skipped/>
  </testcase> <!-- TimeoutOptionTest -->
  <testcase name="Wageringest" classname="Casino.PromotionTest">
    <skipped/>
  </testcase> <!-- Wageringest -->
  <testcase name="TermTest" classname="Casino.GamesLunchTest">
    <skipped/>
  </testcase> <!-- TermTest -->
  <testcase name="HelpAndFAQsTest" classname="Casino.GamesLunchTest">
    <skipped/>
  </testcase> <!-- HelpAndFAQsTest -->
</testsuite> <!-- Cashier.AccountSummary3Test -->
